# Generated by Django 4.0.5 on 2022-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_added_boost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'casual'), (1, 'auto')], default=0),
        ),
        migrations.AlterField(
            model_name='core',
            name='auto_click_power',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
